### ISSUE TITLE
I don't think it is a good idea to involve extensions not related to Xposed

### ISSUE THREAD

**Issue by Dr-TSNG** [KyuubiRan/EzXHelper#11]
Public library should NOT involve public extension functions ESPECIALLY for language standard library. I must admit that this is really outrageous. I think it's better to warn users for this on readme.
https://github.com/KyuubiRan/EzXHelper/blob/16b81d3f726908cbb75501d50bcf3f1f7acba140/EzXHelper/src/main/java/com/github/kyuubiran/ezxhelper/utils/JsonUtils.kt#L38
https://github.com/KyuubiRan/EzXHelper/blob/16b81d3f726908cbb75501d50bcf3f1f7acba140/EzXHelper/src/main/java/com/github/kyuubiran/ezxhelper/utils/Utils.kt#L13
https://github.com/KyuubiRan/EzXHelper/blob/16b81d3f726908cbb75501d50bcf3f1f7acba140/EzXHelper/src/main/java/com/github/kyuubiran/ezxhelper/utils/Utils.kt#L120

**Comment by KyuubiRan** [comment]
a capoo yes sticker

**Comment by QGB** [comment]
what is the difference with https://github.com/fankes/YukiHookAPI ？

@fankes

**Comment by fankes** [comment]
> what is the difference with https://github.com/fankes/YukiHookAPI ？
> 
> @fankes 

No comment. This is not my repo. Please don't reply again. Thank you.

**Comment by andrew-ld** [comment]
lol
