### ISSUE TITLE
Android 13 Support?

### ISSUE THREAD

**Issue by DavidBerdik** [KyuubiRan/EzXHelper#20]
Does this library support Android 13? My module that uses this library is throwing errors saying that a function I want to hook does not exist even though I have verified that it does, and I don't know if I can rule out this library as the source of the problem.

**Comment by keta1** [comment]
@DavidBerdik Can you provide an error log?

**Comment by DavidBerdik** [comment]
@keta1 I have an issue open on my module that contains a stack trace for the issue I am encountering. Perhaps it would be useful for resolving this? - https://github.com/DavidBerdik/MACsposed/issues/1

I can also share an LSposed log dump if you want.

**Comment by DavidBerdik** [comment]
@keta1 Here is an LSposed log dump in case it is useful.

[LSPosed_2022-08-18T00_02_26.295548.zip](https://github.com/Dr-TSNG/Hide-My-Applist/files/9368387/LSPosed_2022-08-18T00_02_26.295548.zip)

**Comment by keta1** [comment]
@DavidBerdik This log contains a lot of private information
Note the desensitization

**Comment by DavidBerdik** [comment]
@keta1 I know it contains information about things like what Magisk modules you have installed and can reveal some detail about Xposed modules you have installed and possibly apps, but at least in my case, none of that information is really all that sensitive. For future reference, which things should I watch out for?

**Comment by keta1** [comment]
https://github.com/DavidBerdik/MACsposed/blob/master/app/src/main/java/com/berdik/macsposed/hookers/SystemUIHooker.kt#L25

https://github.com/LSPosed/LSPosed/blob/master/core/src/main/java/de/robv/android/xposed/XposedHelpers.java#L522

**Comment by DavidBerdik** [comment]
@keta1 The method does exist though.

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:frameworks/base/packages/SystemUI/src/com/android/systemui/qs/QSTileHost.java;l=383

**Comment by keta1** [comment]
It looks like the error is not related to EzXHelper
You find the method through the xposed api

**Comment by DavidBerdik** [comment]
@keta1 Isn't that what EzXHelper is doing though? Anyway, I'll investigate, but it just seems odd. The function was found in Android 12, but not 13 even though, as far as I can tell, nothing has changed. The other function hooks that I have also don't seem to work, but they do not throw any error like this one.

**Comment by keta1** [comment]
Presumably your rom may have modified the code of the system ui

try invoke getDeclaredMethods
and print each one to debug？

**Comment by keta1** [comment]
> @keta1 Isn't that what EzXHelper is doing though? Anyway, I'll investigate, but it just seems odd. The function was found in Android 12, but not 13 even though, as far as I can tell, nothing has changed. The other function hooks that I have also don't seem to work, but they do not throw any error like this one.

EzXHelper provides its own api for finding methods
You didn't use it
Instead, you used the xposed api's

**Comment by DavidBerdik** [comment]
> Presumably your rom may have modified the code of the system ui

I am using the official Google factory image on a Pixel 4a. I would think that the System UI code for that would be the same as AOSP.
 
> try invoke getDeclaredMethods and print each one to debug？

I will. I had not thought to try that.

> EzXHelper provides its own api for finding methods
> You didn't use it
> Instead, you used the xposed api's

But isn't EzXHelper just wrapping the Xposed API for `callMethod()`? - https://github.com/KyuubiRan/EzXHelper/blob/aceb33fcacb82c825e316e34ed91f6decefe6802/EzXHelper/src/main/java/com/github/kyuubiran/ezxhelper/utils/MethodUtils.kt#L602

**Comment by DavidBerdik** [comment]
@keta1 In case you are curious, I managed to get it working. Apparently, Google's AOSP code dump for Android 13 does not have all the changes related to the System UI included in it. I had to decompile the System UI APK from 13 to figure out what to hook.
