### ISSUE TITLE
Unresolved References Error when Using EzXHelper with Gradle Plugin 7.3.0

### ISSUE THREAD

**Issue by DavidBerdik** [KyuubiRan/EzXHelper#21]
It seems that the EzXHelper library doesn't get properly identified as existing when you try to use version 7.3.0 of the Android Gradle Plugin. Android Studio reports that the reference is unresolved, but that is obviously untrue, as the app still builds properly. I am not sure if this is an issue that you can fix, but I wanted to make you aware of it anyway.

![image](https://user-images.githubusercontent.com/7663225/190734699-2c815fc6-173a-43d4-8e9b-5feed6492509.png)

**Comment by keta1** [comment]
Can you display how your gradle dependencies are configured?

**Comment by DavidBerdik** [comment]
Certainly! The source code for the app that this screenshot is taken from is open source, so I can share the whole thing.

https://github.com/DavidBerdik/MACsposed

**Comment by keta1** [comment]
> Certainly! The source code for the app that this screenshot is taken from is open source, so I can share the whole thing.
> 
> https://github.com/DavidBerdik/MACsposed

https://github.com/DavidBerdik/MACsposed/blob/master/app/build.gradle#L37

https://github.com/DavidBerdik/MACsposed/blob/master/app/build.gradle#L39

please delete these two lines

**Comment by keta1** [comment]
> Certainly! The source code for the app that this screenshot is taken from is open source, so I can share the whole thing.
> 
> https://github.com/DavidBerdik/MACsposed

https://github.com/DavidBerdik/MACsposed/blob/master/app/build.gradle#L37

https://github.com/DavidBerdik/MACsposed/blob/master/app/build.gradle#L39

delete these two lines

**Comment by DavidBerdik** [comment]
That seems to have worked! Why are the `:sources` lines a problem? I'd seen a recommendation somewhere to include them, but I have never understood their purpose.

**Comment by keta1** [comment]
It looks like the dependency is assigned a classifier of sources
This allows gradle to download the source code during the sync phase

**Comment by keta1** [comment]
I've never written this before.
idea can find the source code to download by itself.
I can see the correct source code when I jump to the declaration

**Comment by keta1** [comment]
In the past, you did not make mistakes in these writings, but about six months ago it started to make mistakes

**Comment by DavidBerdik** [comment]
I'm still not sure I entirely understand the issue. I know it's been a problem for at least a couple months now, but I thought it was a bug with the Gradle plugin when I first saw it, so I reverted without giving it any thought.

**Comment by keta1** [comment]
@DavidBerdik Except for xposed-related projects, I didn't see it written in the dependencies: sources, it seems that you are all misled by the outdated blog

**Comment by DavidBerdik** [comment]
Fair enough. Anyway, since this issue is resolved, I will close this. Thank you for your help!
