### ISSUE TITLE
建议：想要提供获取R对象中的各个id

### ISSUE THREAD

**Issue by LiuYiGL** [KyuubiRan/EzXHelper#32]
最近在开发的时候需要使用`id name`获取控件的或者布局的`id`。

我知道已经提供了一个ViewUtils去通过`id name`获取`id`，但是这个对针对已经实例化的ViewGroup对象去获取。

比如说我有个需求就是使用id去inflate一个实例，但是，这个id是需要自己用变量去记录，感觉挺麻烦的。
希望在`EzXHepler`类下可以多一个使用`id name`获取 相对应`id` 的

例子：
>类名：`包名.R.layout`
```java
public static final class layout 
{
        public static final int abc_action_bar_title_item = 0x7f0d0000;
        public static final int abc_action_bar_up_container = 0x7f0d0001;
        public static final int abc_action_menu_item_layout = 0x7f0d0002;
}
```

我的实现逻辑是：
```java
public int getLayoutId(XC_LoadPackage.LoadPackageParam loadPackageParam, String idName) {
    Class<?> layoutClazz = XposedHelpers
            .findClass(loadPackageParam.packageName + ".R.layout", loadPackageParam.classLoader);
    return XposedHelpers.getStaticIntField(layoutClazz, idName);
}
```

封装起来会方便很多

**Comment by keta1** [comment]
https://kyuubiran.github.io/EzXHelper/-ez-x-helper/com.github.kyuubiran.ezxhelper.misc/-view-utils/get-id-by-name.html

**Comment by LiuYiGL** [comment]
嗯嗯 刚刚看到作者其实完成获取通过`name` 找 `id` 的方法，
源码是：
```kotlin
    /**
     * Find id by name
     * @param name R.id.[name]
     * @return id found id or 0 if not found
     */
    @SuppressLint("DiscouragedApi")
    @JvmStatic
    fun getIdByName(name: String, ctx: Context = EzXHelper.appContext): Int {
        return ctx.resources.getIdentifier(name, "id", ctx.packageName)
    }
```

看源码似乎是针对 `R.id` 下的。
希望增加更多类型比如 `R.layout`、`R.string` 下这些

**Comment by KyuubiRan** [comment]
> 嗯嗯 刚刚看到作者其实完成获取通过`name` 找 `id` 的方法， 源码是：
> 
> ```kotlin
>     /**
>      * Find id by name
>      * @param name R.id.[name]
>      * @return id found id or 0 if not found
>      */
>     @SuppressLint("DiscouragedApi")
>     @JvmStatic
>     fun getIdByName(name: String, ctx: Context = EzXHelper.appContext): Int {
>         return ctx.resources.getIdentifier(name, "id", ctx.packageName)
>     }
> ```
> 
> 看源码似乎是针对 `R.id` 下的。 希望增加更多类型比如 `R.layout`、`R.string` 下这些

之后会改成自选的
