### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by drakulaboy** [KyuubiRan/EzXHelper#6]
i'm new to Kotlin but i know how to work with java and xposed module, can you show me for example how to make [this last code in kotlin](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial#final-steps-execute-your-own-code-beforeafter-the-method-call) and [this one](https://github.com/rovo89/XposedBridge/wiki/Replacing-resources#modifying-layouts) , thank you very much!

**Comment by keta1** [comment]
You can refer to [qqcleaner](https://github.com/KyuubiRan/QQCleaner)
The library is still under active development and the API is not very stable

**Comment by keta1** [comment]
See branch 2.0 for details code
https://github.com/KyuubiRan/QQCleaner/tree/2.0/app%2Fsrc%2Fmain%2Fjava%2Fme%2Fkyuubiran%2Fqqcleaner%2Fhook
branch master is outdate.

**Comment by KyuubiRan** [comment]
First you need call EzXHelperInit.initHandleLoadPackage such as [this](https://github.com/KyuubiRan/QQCleaner/blob/2.0/app/src/main/java/me/kyuubiran/qqcleaner/HookEntry.kt)

**Comment by KyuubiRan** [comment]
Then you can use it just like the [example.png](https://github.com/KyuubiRan/EzXHelper/blob/master/docs/example.png) after-part

**Comment by drakulaboy** [comment]
> branch master is outdate.

that's why i didn't make it, i was using the master branch, lol, thank you very much

**Comment by KyuubiRan** [comment]
I created a template for this library:
https://github.com/KyuubiRan/ezxhepler-template
